function [DataAsOf, StartDate, EndDate, Group, Year, Month, MMWRWeek, WeekEndingDate, State, ... 
    COVID19Deaths, TotalDeaths1, PercentOfExpectedDeaths, PneumoniaDeaths, ...
     PneumoniaAndCOVID19Deaths, InfluenzaDeaths, PneumoniaInfluenzaOrCOVID19Deaths, Footnote] = ...
     importfile_cdc_mort(filename, dataLines)
     
    %IMPORTFILE Import data from a text file
    %  [DATAASOF, STARTDATE, ENDDATE, GROUP, YEAR, MONTH, MMWRWEEK,
    %  WEEKENDINGDATE, STATE, COVID19DEATHS, TOTALDEATHS1,
    %  PERCENTOFEXPECTEDDEATHS, PNEUMONIADEATHS, PNEUMONIAANDCOVID19DEATHS,
    %  INFLUENZADEATHS, PNEUMONIAINFLUENZAORCOVID19DEATHS, FOOTNOTE] =
    %  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
    %  default selection.  Returns the data as column vectors.
    %
    %  [DATAASOF, STARTDATE, ENDDATE, GROUP, YEAR, MONTH, MMWRWEEK,
    %  WEEKENDINGDATE, STATE, COVID19DEATHS, TOTALDEATHS1,
    %  PERCENTOFEXPECTEDDEATHS, PNEUMONIADEATHS, PNEUMONIAANDCOVID19DEATHS,
    %  INFLUENZADEATHS, PNEUMONIAINFLUENZAORCOVID19DEATHS, FOOTNOTE] =
    %  IMPORTFILE(FILE, DATALINES) reads data for the specified row
    %  interval(s) of text file FILENAME. Specify DATALINES as a positive
    %  scalar integer or a N-by-2 array of positive scalar integers for
    %  dis-contiguous row intervals.
    %
    %  Example:
    %  [DataAsOf, StartDate, EndDate, Group, Year, Month, MMWRWeek, WeekEndingDate, State, COVID19Deaths, TotalDeaths1, PercentOfExpectedDeaths, PneumoniaDeaths, PneumoniaAndCOVID19Deaths, InfluenzaDeaths, PneumoniaInfluenzaOrCOVID19Deaths, Footnote] = importfile("D:\DATA\CDC\Provisional_COVID-19_Death_Counts_by_Week_Ending_Date_and_State_20240303.csv", [2, Inf]);
    %
    %  See also READTABLE.
    %
    % Auto-generated by MATLAB on 03-Mar-2024 08:08:27
    
    %% Input handling
    
    % If dataLines is not specified, define defaults
    if nargin < 2
        dataLines = [2, Inf];
    end
    
    %% Set up the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 17);
    
    % Specify range and delimiter
    opts.DataLines = dataLines;
    opts.Delimiter = ",";
    
    % Specify column names and types
    opts.VariableNames = ["DataAsOf", "StartDate", "EndDate", "Group", "Year", "Month", "MMWRWeek", "WeekEndingDate", "State", "COVID19Deaths", "TotalDeaths1", "PercentOfExpectedDeaths", "PneumoniaDeaths", "PneumoniaAndCOVID19Deaths", "InfluenzaDeaths", "PneumoniaInfluenzaOrCOVID19Deaths", "Footnote"];
    opts.VariableTypes = ["datetime", "datetime", "datetime", "categorical", "string", "string", "double", "datetime", "categorical", "double", "double", "double", "double", "double", "double", "double", "string"];
    
    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";
    
    % Specify variable properties
    opts = setvaropts(opts, ["Year", "Month", "Footnote"], "WhitespaceRule", "preserve");
    opts = setvaropts(opts, ["Group", "Year", "Month", "State", "Footnote"], "EmptyFieldRule", "auto");
    opts = setvaropts(opts, "DataAsOf", "InputFormat", "MM/dd/yyyy");
    opts = setvaropts(opts, "StartDate", "InputFormat", "MM/dd/yyyy");
    opts = setvaropts(opts, "EndDate", "InputFormat", "MM/dd/yyyy");
    opts = setvaropts(opts, "WeekEndingDate", "InputFormat", "MM/dd/yyyy");
    
    % Import the data
    tbl = readtable(filename, opts);
    
    %% Convert to output type
    DataAsOf = tbl.DataAsOf;
    StartDate = tbl.StartDate;
    EndDate = tbl.EndDate;
    Group = tbl.Group;
    Year = tbl.Year;
    Month = tbl.Month;
    MMWRWeek = tbl.MMWRWeek;
    WeekEndingDate = tbl.WeekEndingDate;
    State = tbl.State;
    COVID19Deaths = tbl.COVID19Deaths;
    TotalDeaths1 = tbl.TotalDeaths1;
    PercentOfExpectedDeaths = tbl.PercentOfExpectedDeaths;
    PneumoniaDeaths = tbl.PneumoniaDeaths;
    PneumoniaAndCOVID19Deaths = tbl.PneumoniaAndCOVID19Deaths;
    InfluenzaDeaths = tbl.InfluenzaDeaths;
    PneumoniaInfluenzaOrCOVID19Deaths = tbl.PneumoniaInfluenzaOrCOVID19Deaths;
    Footnote = tbl.Footnote;
    end